add admin informations to /v1/version
ysakasin/bcdice-api pull request #17
Opened 2020-03-22 08:36 UTC by koi-chan

/v1/version に、サーバ管理者の情報を出力できるようにしました。
提供者名とそのサーバの利用規約・連絡先を書いたURLを返すことを意図しています。

ご確認いただきますようお願い致します。

2020-03-22 09:20 UTC, ysakasin commented
@koi-chan PRありがとうございます。

正直、この機能のサポートは否定的です。管理者が"適切に"設定すべき内容なので、結局設定されずに困るなんてことが起こりそうだからです。BCDice-APIのサーバーを立てるのは、技術に明るい人だけではないので。

以下、いくつか気になった点です。

### エンドポイント
`/v1/version` に含めるよりも、 `/v1/admin` を新設してした方が適切なようにも思えますが、 しいて`/v1/version` に含める意図があれば教えてください。

### 設定方法
ファイルへの記述だけでなく、環境変数からも設定できるようにして欲しいです。
Herokuへのデプロイ時に面倒なことになってしまいます。
YAMLと環境変数が両方ある場合には環境変数を優先して欲しいです。

2020-03-22 09:22 UTC, ysakasin commented
あと、この情報の利用用途があまり把握できてないので、利用用途について補足あればお教えください。

2020-03-22 10:54 UTC, ochaochaocha3 commented
PRの方針に賛成します。

一般に、Webサービスを運営する際は、運営者情報と利用規約をよく提示します。BCDice-APIは複数箇所に設置されるため、運営者情報と利用規約も設置者によって必然的に変わります。そのため、これらの情報を実際に動作しているサーバプログラムから何らかの手段で参照できるようにすることは、トラブル発生時に対応しやすくするという意味で、有意義です。

> 管理者が"適切に"設定すべき内容なので、結局設定されずに困るなんてことが起こりそう

コードを見てみると、設定しなかった場合は `nil` になるので、運営者情報と利用規約はともにoptionalな項目（大手のサーバは設定する、身内で使うだけならば設定の必要なし）とすれば、実運用上は問題ないと思いました。

エンドポイント、および設定方法については、@ysakasin さんと同意見です。

2020-03-22 11:58 UTC, ochaochaocha3 commented
設定読み込み処理は一応動きますが、クラス定義に読み込み処理があると、再読み込みやテストが行いにくいため、設定用のクラスを作るとより良いと思います。これを構造体で作ると、`#to_h` での変換も自動で用意してくれるので、便利です。

（以下、動作確認済みの変更案です）

```ruby
# lib/bcdice_api/administrator.rb
require 'yaml'

module BCDiceAPI
  class << self
    # 運営者情報
    # @return [Administrator]
    attr_accessor :admin
  end

  # 運営者情報を表す構造体
  # @!attribute name
  #   @return [String] 運営者名
  # @!attribute address
  #   @return [String] 連絡先のURLやメールアドレス
  Administrator = Struct.new(:name, :address) do
    # YAMLファイルと環境変数から読み込む
    # @param [String] yaml_file YAMLファイルのパス
    # @return [Administrator]
    def self.load_from_yaml_and_env(yaml_file)
      admin = new

      if File.exist?(yaml_file)
        admin_hash = YAML.load_file(yaml_file)
        admin.update_with_hash_from_yaml!(admin_hash)
      end

      admin.update_with_env!

      admin
    end

    # YAMLから変換したHashを使用して情報を更新する
    # @return [self]
    def update_with_hash_from_yaml!(hash)
      self.name = hash['admin_name']
      self.address = hash['admin_address']

      self
    end

    # 環境変数を使用して情報を更新する
    # @return [self]
    def update_with_env!
      name = ENV['BCDICE_API_ADMIN_NAME']
      self.name = name if name

      address = ENV['BCDICE_API_ADMIN_ADDRESS']
      self.address = address if address

      self
    end
  end
end

# server.rb
require 'bcdice_api/administrator'

# ...

# ファイル末尾：設定を運営者情報を読み込む
admin_yaml = File.expand_path('config/admin.yaml', __dir__)
BCDiceAPI.admin = BCDiceAPI::Administrator.load_from_yaml_and_env(admin_yaml)

# GETのどこかで BCDiceAPI.admin.to_h を使う
```

2020-03-22 16:46 UTC, koi-chan commented
早速のご確認を頂きありがとうございます。
エンドポイントの変更、環境変数による設定、設定用のクラスの作成について、改良したものを準備致します。

この機能の利用用途としては、基本的に他のツールのバックエンドとして使われるため利用者からは見えにくい API サービスを広く公開して提供するとき、API 提供者の身を守る道具として機能することを意図しています。
利用者自身や API を使う他のツール作成者・提供者などが API 提供者の利益を損なうような利用をしたとき、API 提供者が身を守る手段の一つとして(読まれるかどうかは別として)利用規約や使い方など、利用者が使うに当たって注意すべき項目を掲げる行動が挙げられます。
これらの利用規約等にアクセスしやすくすることは、API プログラムとして重要ではないかと考えます。

確かに懸念されているとおり、管理者が適切に設定しなければ無用の機能ではあります。
しかし、適切な設定がされているかどうかは、ある API が公開サービスかそうでないかをツール作成者・提供者が判別しやすくしたり、利用者が(安定性や管理されているかなどを考慮して)どの API サーバを利用するかを検討したりするための材料になり得ると思います。

2020-03-23 05:15 UTC, ysakasin commented
Structを使わずとも、ロード処理を特異メソッドに切り出せばいいと思います。

2020-03-23 05:16 UTC, ysakasin commented
```ruby
module BCDiceAPI
  def self.load_something
    ...
  end

  ADMIN = load_something
end
```

2020-03-24 11:05 UTC, ysakasin commented
Discord等での議論を通じて、この機能がある方が便利であると私も理解できたので、提案を受け入れます。

2020-03-24 11:21 UTC, ysakasin requested changes

2020-03-24 11:21 UTC, ysakasin commented on lib/load_config.rb
> +    )
```suggestion
    config = {}
    
    if File.exist?(path)
      yaml = YAML.load_file(path)
      config = {
        name: yaml['name'],
        url: yaml['url'],
        email: yaml['email'],
      }.compact
    end
    
    config[:name] = ENV['BCDICE_API_ADMIN_NAME'] if ENV['BCDICE_API_ADMIN_NAME']
    config[:url] = ENV['BCDICE_API_ADMIN_URL'] if ENV['BCDICE_API_ADMIN_URL']
    config[:email] = ENV['BCDICE_API_ADMIN_EMAIL'] if ENV['BCDICE_API_ADMIN_EMAIL']

    config
```

初期値を明示して、そこから上書きしていくスタイルの方が読みやすそうです。

2020-03-24 11:21 UTC, ysakasin commented on lib/load_config.rb
> +  def self.load_config
`load_config` だとなんの設定を読みだすのがわからないので、 `load_admin_info` あたりが妥当だと思います。ファイル名も同様に変更お願いします。

2020-03-24 11:21 UTC, ysakasin commented on config/admin.yaml.example
> +admin_address: ''
このYAMLに書かれる項目はおそらく全て `admin` がつくことになってしまうので、単に `name` のようにしていいと思います。

2020-03-24 11:21 UTC, ysakasin commented on docs/api.md
> +  "address": "https://your-information-page/url"
`address`はURLやメールアドレスを想定しているとのことですが、揺らぎがあるとツール側での扱いに困りやすいので、`url`と`email`に分割するのが良いと思うのですがどうでしょう？

2020-03-24 12:51 UTC, koi-chan commented on lib/load_config.rb
> +    )
修正案15行目の compact により、設定されていない場合にこのエンドポイントが何も項目を持たないことになってしまいます。
クライアント側の処理が面倒になると思うので API では明示的に null を返す方がより良いと考えますが、いかがでしょうか。

2020-03-24 12:51 UTC, koi-chan commented
再び確認頂きありがとうございます。
修正したものを push 致します。

2020-03-24 12:59 UTC, koi-chan commented on docs/api.md
> +  "address": "https://your-information-page/url"
分割するようにしました。

2020-03-24 13:00 UTC, koi-chan commented on config/admin.yaml.example
> +admin_address: ''
項目名については admin を付けるかどうか悩んでいたところではありましたので、削ることにしました。

2020-03-24 13:00 UTC, koi-chan commented on lib/load_config.rb
> +  def self.load_config
修正しました。

2020-03-24 13:37 UTC, ysakasin commented on lib/load_config.rb
> +    )
suggestを書いた時点では指定しない場合は、項目自体がなくて良いと思ってそう書いていました。nullを返すよりも、設定されていないものは空白文字`""`を返すというのが良さそうなのですが、どうでしょう。

SlackやGitHubのWebAPIを見てみましたが、設定されていないものは空文字で返すというのが一般的なようです。
- https://api.slack.com/methods/users.list
- https://developer.github.com/v3/users/

2020-03-24 13:50 UTC, ysakasin commented on lib/load_config.rb
> +    )
yamlの方で、各要素を`to_s`して入れておけば `nil` でも勝手に空白になるのと、文字列であることを保証できて一石二鳥かもしれません

2020-03-24 14:02 UTC, koi-chan commented on lib/load_config.rb
> +    )
なるほど、調査までして頂きありがとうございます。
では、設定されていなかった場合は空文字列を入れるようにします。

2020-03-25 14:22 UTC, ysakasin requested changes

2020-03-25 14:22 UTC, ysakasin commented on lib/load_admin_info.rb
> +    config = {}
```suggestion
    config = {
      name: '',
      url: '',
      email: '',
    }
```

ここで初期化しておかないと、何も設定してない時に表示されません

2020-03-25 14:22 UTC, ysakasin commented on lib/load_admin_info.rb
> +    config[:email] = ENV['BCDiceAPI_ADMIN_EMAIL'] if ENV['BCDiceAPI_ADMIN_EMAIL']
```suggestion
    config[:name] = ENV['BCDICE_API_ADMIN_NAME'] if ENV['BCDICE_API_ADMIN_NAME']
    config[:url] = ENV['BCDICE_API_ADMIN_URL'] if ENV['BCDICE_API_ADMIN_URL']
    config[:email] = ENV['BCDICE_API_ADMIN_EMAIL'] if ENV['BCDICE_API_ADMIN_EMAIL']
```

環境変数は慣例に倣って大文字でお願いします

2020-03-25 15:09 UTC, ysakasin commented on lib/load_admin_info.rb
> +    config[:email] = ENV['BCDICEAPI_ADMIN_EMAIL'] if ENV['BCDICEAPI_ADMIN_EMAIL']
```suggestion
    config[:name] = ENV['BCDICE_API_ADMIN_NAME'] if ENV['BCDICE_API_ADMIN_NAME']
    config[:url] = ENV['BCDICE_API_ADMIN_URL'] if ENV['BCDICE_API_ADMIN_URL']
    config[:email] = ENV['BCDICE_API_ADMIN_EMAIL'] if ENV['BCDICE_API_ADMIN_EMAIL']
```

2020-03-25 15:10 UTC, ysakasin approved these changes

2020-03-25 15:11 UTC, merged