計算コマンドに対応する
ysakasin/bcdice-api pull request #8
Opened 2019-07-15 05:19 UTC by ochaochaocha3

これまで実行できなかった計算コマンド `C(...)` を実行できるようにしました。これにより、QuoridornなどのBCDice APIを使用するTRPGツールでも、どどんとふと同様に四則演算の結果を確認することができるようになります。

# 実行例

<img width="1022" alt="bcdice-api_support_calc" src="https://user-images.githubusercontent.com/2551173/61196661-31977880-a70b-11e9-9045-f07fb79f3a09.png">

2019-07-15 11:50 UTC, ysakasin requested changes

2019-07-15 11:50 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
- splitせずに `%r{^C\([-+*/()\d]+\)\z}i` だけをテストすればよさそう
  - `s.split(/\s/)` の先頭がコマンドになっているということは、sは空白から始まっていない
- チェックには `Regexp#match?` を用いてください
  - https://docs.ruby-lang.org/ja/latest/method/Regexp/i/match=3f.html

2019-07-15 11:50 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    return "#{@diceBot.gameType} : 計算結果 ＞ #{calc_result}", false
BCDice-APIでは結果の頭に `gameType` をつけていないので、この挙動は誤りです。

2019-07-15 11:50 UTC, ysakasin commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
このチェックは `try_calc_command` に含めていいと思います。ネストを浅くできるのと、`try_calc_command` も結局は `nil, nil` を返す可能性があるので。

2019-07-15 11:50 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    matches = stripped_message.match(/\AC([-\d]+\z)/i)
より正確に `/\AC(-?\d+)\z/i` の方が良いかと思います。

2019-07-15 11:51 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
もしくは、もっと省略して `String#start_with?` を使ってもいいかもしれません

2019-07-15 12:47 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    return "#{@diceBot.gameType} : 計算結果 ＞ #{calc_result}", false
`": 計算結果 ＞ #{calc_result}"`が期待される挙動です

2019-07-15 13:11 UTC, ochaochaocha3 commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
> * splitせずに `%r{^C\([-+*/()\d]+\)\z}i` だけをテストすればよさそう
>     * `s.split(/\s/)` の先頭がコマンドになっているということは、sは空白から始まっていない

基本的にはBCDiceからそのまま持ってきたものです。BCDiceでは以下の `C(10+5) mokekeke` のような入力も通りますが、そのように変更すると通らなくならないでしょうか？

https://github.com/bcdice/BCDice/blob/f8881ea551565592580bb1dd9d8348f2d2cdfb58/src/test/data/None.txt#L229-L233

> * チェックには `Regexp#match?` を用いてください
>       * https://docs.ruby-lang.org/ja/latest/method/Regexp/i/match=3f.html

`Regexp#match?` はRuby 2.4の新機能だそうです。導入するとRuby 2.4以降のみの対応に変わりますが、よろしいでしょうか？

https://qiita.com/jnchito/items/9f9d45581816f121af07#%E6%AD%A3%E8%A6%8F%E8%A1%A8%E7%8F%BE%E3%81%AB%E6%96%87%E5%AD%97%E5%88%97%E3%81%8C%E3%83%9E%E3%83%83%E3%83%81%E3%81%97%E3%81%9F%E3%81%8B%E3%81%A9%E3%81%86%E3%81%8B%E3%81%A0%E3%81%91%E3%82%92%E8%BF%94%E3%81%99regexpmatchstringmatchsymbolmatch

2019-07-15 13:13 UTC, ochaochaocha3 commented on lib/bcdice_wrap.rb
> +    return "#{@diceBot.gameType} : 計算結果 ＞ #{calc_result}", false
勘違いでした。修正いたします。

2019-07-15 13:13 UTC, ochaochaocha3 commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
そのように変更いたします。

2019-07-15 13:13 UTC, ochaochaocha3 commented on lib/bcdice_wrap.rb
> +    matches = stripped_message.match(/\AC([-\d]+\z)/i)
そのように変更いたします。

2019-07-15 13:51 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
`\z`の仕様を勘違いしていました。 `%r{^C\([-+*/()\d]+\)}i` にすればよさそうです。

2019-07-15 13:55 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
Ruby 2.3はEOLなので、サポートから外そうと思います。`Regexp#match?` を用いて大丈夫です。

このままだとCIにRuby 2.3があることでテストが落ちると思いますので、CIの設定からRuby 2.3を消してもらえますか？

2019-07-15 14:35 UTC, ochaochaocha3 commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
コメントありがとうございます。以上のように修正いたします。

2019-07-15 14:43 UTC, ochaochaocha3 commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
この変更は無理でした。`try_calc_command` では括弧内前処理が完了しているので、`@message` が `C123` のように `/C-?\d+/` の形になっており、判定できませんでした。

2019-07-15 14:51 UTC, ysakasin commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
`try_calc_command` が元のコマンドを引数で受け取れば良いと思っていたのですが、それだと見通しが悪いでしょうか？

2019-07-15 14:59 UTC, ochaochaocha3 commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
すみません、BCDiceの挙動と合わせるためには、やはり `String#split` 相当の処理が必要でした。単純な前方マッチは次の両方の場合にマッチしますが、計算コマンドかどうかをBCDiceの挙動通りに正しく判定できませんでした。

* `C(10+5)mokeke`（間に半角空白なし）：BCDiceでは反応しない -> `seem_to_be_calc?` は `false` にしたい
* `C(10+5) mokeke`（間に半角空白あり）：BCDiceでは反応する -> `seem_to_be_calc?` は `true` にしたい

2019-07-15 15:19 UTC, ochaochaocha3 commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
> `try_calc_command` が元のコマンドを引数で受け取れば良いと思っていたのですが、それだと見通しが悪いでしょうか？

これはできなさそうです。その理由は、BCDiceには計算コマンド `C(...)` 用の特別な処理が含まれていないからです。計算コマンドの実態は、括弧内前処理の結果として `C(...)` の括弧部分が勝手にただの整数に変換されて `C整数` となった後で、「整数」の部分を取り出す処理です。そのため、正規表現 `C(-?\d+)` が出てきます。元のコマンドを引数で受け取るのは確かにやりたいことなのですが、dengineやGoBCDiceで実装しているような構文解析器が要りそうです😇

`try_calc_command` はBCDiceの
https://github.com/bcdice/BCDice/blob/f8881ea551565592580bb1dd9d8348f2d2cdfb58/src/bcdiceCore.rb#L631-L637
に相当する処理で、とりあえずこれを移しておけば動くだろうという判断でした。

2019-07-15 16:15 UTC, ysakasin commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
それは把握していますが、広い方に互換性があるので、bcdice-apiとしては `C(10+5)mokeke` を許容してもいいと思います。

2019-07-15 16:18 UTC, ysakasin commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
```
    if result.nil?
      result, secret = bcdice.try_calc_command(command)
    end
```

という意図だったのですが、書けないのでしょうか？

2019-07-15 23:53 UTC, ochaochaocha3 commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
分かりました。それでは、テストケースも含めて許容するように変えてみます。

2019-07-15 23:57 UTC, ochaochaocha3 commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
すみません、意図をきちんと読み取れていませんでした。以下のようにすれば確かにできそうです。

```ruby
class BCDice
  def try_calc_command(command)
    unless self.class.seem_to_be_calc?(command)
      return nil, nil
    end

    # 以下では @message を使って計算結果を返す
  end
end
```

2019-07-16 03:08 UTC, ochaochaocha3 commented on lib/bcdice_wrap.rb
> +    return %r{\AC\([-+*/()\d]+\)\z}i === target
83d1e0154a3f1d3900216a8ac1f518e7805d3c15 で正規表現パターンを変更しました。

2019-07-16 03:09 UTC, ochaochaocha3 commented on server.rb
> +      if BCDice.seem_to_be_calc?(command)
33a1ffe7c7310cce9d894a8c7f13b5091b476523 で上記のようにインターフェースを変更しました。

2019-07-16 13:27 UTC, ysakasin approved these changes

2019-07-16 13:27 UTC, merged

2019-07-16 13:27 UTC, ysakasin commented
ありがとうございます。マージしました。

2019-07-16 13:41 UTC, ochaochaocha3 commented
こちらこそ、丁寧にレビューしていただき、ありがとうございました。